# Default values for helm-demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

serviceAccount:
  create: true
  annotations: {}
  name: "guestbook-sa"

nameOverride: ""
fullnameOverride: ""

backend:
  name: redis

  master:
    name: master
    replicaCount: 1
    image:
      repository: k8s.gcr.io/redis
      pullPolicy: IfNotPresent
      tag: e2e
    labels:
      app: redis
      role: master
      tier: backend
    podAnnotations: {}
    podSecurityContext: {}
    securityContext: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
    env: {}
    service:
      type: ClusterIP
      port: 6379
      protocol: TCP
      name: redis
    resources: 
      requests:
        cpu: 100m
        memory: 100Mi

  slave:
    name: replica
    replicaCount: 2
    image:
      repository: gcr.io/google_samples/gb-redisslave
      pullPolicy: IfNotPresent
      tag: v1
    labels:
      app: redis
      role: slave
      tier: backend
    podAnnotations: {}
    podSecurityContext: {}
    securityContext: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
    env: 
    - name: GET_HOSTS_FROM
      value: dns
    service:
      type: ClusterIP
      port: 6379
    resources: {}

frontend:

  name: frontend

  replicaCount: 3
  image:
    repository: gcr.io/google-samples/gb-frontend
    pullPolicy: IfNotPresent
    tag: v4
    containerName: php-redis
  labels:
    app: guestbook
    tier: frontend
  imagePullSecrets: []
  podAnnotations: ""
  podSecurityContext: {}
  securityContext: {}
  service:
    type: ClusterIP
    port: 80
  env:
    - name: GET_HOSTS_FROM
      value: dns
  resources: 
    requests:
      cpu: 100m
      memory: 100Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: azure/application-gateway
      appgw.ingress.kubernetes.io/backend-path-prefix: "/"
    hosts:
      - host: guestbook
        paths:
        - path: /guestbook
          backend:
            serviceName: frontend
            servicePort: 80
    tls: []