# master
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.master.name }}
spec:
  selector:
    matchLabels:
      {{- toYaml .Values.backend.master.labels | nindent 8 }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.backend.master.labels | nindent 8 }}
    spec:
      serviceAccountName: {{ include "helm-demo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.backend.master.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.backend.master.image.repository }}:{{ .Values.backend.master.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.master.image.pullPolicy}}
          ports:
            - name: {{ .Values.backend.master.service.name }}
              containerPort: {{ .Values.backend.master.service.port }}
              protocol: {{ .Values.backend.master.service.protocol }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.backend.master.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: {{ .Values.backend.master.service.port }}
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.backend.master.resources | nindent 12 }}
          env:
            {{- range .Values.backend.slave.env }}
            - name: {{ .name }}
              value: {{ .value }}  
            {{- end }}
      {{- with .Values.backend.master.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.master.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.master.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
# slave
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}-replica
spec:
  selector:
    matchLabels:
      {{- toYaml .Values.backend.slave.labels | nindent 8 }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.backend.slave.labels | nindent 8 }}
    spec:
      serviceAccountName: {{ include "helm-demo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.backend.slave.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.backend.slave.image.repository }}:{{ .Values.backend.slave.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.slave.image.pullPolicy}}
          ports:
            - name: {{ .Values.backend.slave.service.name }}
              containerPort: {{ .Values.backend.slave.service.port }}
              protocol: {{ .Values.backend.slave.service.protocol }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.backend.slave.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: {{ .Values.backend.slave.service.port }}
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.backend.slave.resources | nindent 12 }}
          env:
            {{- range .Values.backend.slave.env }}
            - name: {{ .name }}
              value: {{ .value }}  
            {{- end }}
      {{- with .Values.backend.slave.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.slave.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.slave.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
# frontend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      {{- toYaml .Values.frontend.labels | nindent 8 }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.frontend.labels | nindent 8 }}
    spec:
      {{- with .Values.frontend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helm-demo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.frontend.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.frontend.image.containerName }}
          securityContext:
            {{- toYaml .Values.frontend.securityContext | nindent 12 }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: {{ .Values.frontend.service.name }}
              containerPort: {{ .Values.frontend.service.port }}
              protocol: {{ .Values.frontend.service.protocol }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.frontend.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: {{ .Values.frontend.service.port }}
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          env:
            {{- range .Values.backend.slave.env }}
            - name: {{ .name }}
              value: {{ .value }}  
            {{- end }}
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}